<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <InvariantGlobalization>false</InvariantGlobalization>
    <UserSecretsId>85e38ee3-8fea-4e79-97ff-db13bef9846d</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElBruno.LocalEmbeddings" Version="1.4.6" />
    <PackageReference Include="Npgsql" Version="10.0.2" />
    <PackageReference Include="Pgvector" Version="0.3.2" />
    <PackageReference Include="QuestPDF" Version="2025.7.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="**/._*.cs" />
    <Content Remove="**/._*" />
    <None Remove="**/._*" />
  </ItemGroup>
</Project>
